[project]
name = "scheduler-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.14",
    "openai-agents>=0.0.4",
<<<<<<< Updated upstream
    "python-dotenv>=1.0.1",
=======
    "python-dotenv>=1.1.1",
>>>>>>> Stashed changes
]
